# Generated by Django 4.2.20 on 2025-05-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_attached_files'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='agents', to='tickets.category'),
        ),
    ]
