# Generated by Django 4.2.20 on 2025-05-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attached_files',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
